### ISSUE TITLE
Make debugging easier

### ISSUE THREAD

**Issue by jclem** [actions/github-script#1]
Currently, it's really difficult to determine where an error occurred in a user's `script` input, because of how it's evaluated.

One option for improving this might be two wrap the user script in a string for creating the async function, and then writing that to a file and executing it.

**Comment by jcansdale** [comment]
I wonder if source-maps could be used here? 🤔 
https://survivejs.com/webpack/building/source-maps/

**Comment by jclem** [comment]
I'm closing this—the line/column for the `anonymous` function in stack traces is actually accurate.

![Screen Shot 2020-02-28 at 10 05 54 AM](https://user-images.githubusercontent.com/412282/75559864-3b5bbb00-5a12-11ea-9630-267862cce392.png)

@jcansdale To your point about source maps, they wouldn't help in this case, because the user scripts themselves aren't transpiled, so source maps wouldn't add any clarity around errors in the eval'd functions.

**Comment by afwn90cj93201nixr2e1re** [comment]
@jclem 
![изображение](https://user-images.githubusercontent.com/9306996/79063515-bced6c80-7c91-11ea-9128-6c3197267b67.png)

SyntaxError: Invalid or unexpected token

same with single quotes. So, what's the problem?

**Comment by afwn90cj93201nixr2e1re** [comment]
```
on:
    issue_comment:
        types: [created]

            - name: Prepare comment file
              run: |
                echo -e "[${{github.event.comment.user.login}}](${{github.event.comment.user.url}}) tryna get copy for ${{env.IP_ADDR}}\n\n\nYou can try to get artifact from: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}" > git_comment.txt

            - name: Create comment context1
              if: always()
              shell: bash
              run: |
                REPORT="$(cat git_comment.txt)"
                REPORT="${REPORT//'%'/'%25'}"
                REPORT="${REPORT//$'\n'/'%0A'}"
                REPORT="${REPORT//$'\r'/'%0D'}"
                echo "::set-env name=comment::$REPORT"  

            - uses: actions/github-script@0.9.0
              if: always()
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.issues.createComment({
                        issue_number: ${{ github.event.issue.number }},
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: "${{ env.comment }}"
                    })
```

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/79063696-ac89c180-7c92-11ea-95b1-a85f549ea988.png)
https://github.com/marketplace/actions/create-or-update-comment
btw this extension works well.

**Comment by adbl** [comment]
@afwn90cj93201nixr2e1re did you figure out what this problem is about?

**Comment by afwn90cj93201nixr2e1re** [comment]
No, as you can see above, I just used another extension

**Comment by jclem** [comment]
What's the content of the report? Double quotes, for example, would cause a syntax error.

**Comment by adbl** [comment]
I'd expect any escaping needed to be done automatically. Seems weird for context data to be evaluated like script code. Are there use cases for writing script logic that way?

**Comment by jclem** [comment]
The issue is that ${{}} interpolation is performed by Actions before the script content is sent to this particular action. When the github-script actions receives the script, the interpolation has already been completed and I have no way of knowing which parts of it interpolated.

This is a limitation of implementing this action in user-space, essentially. It's not a design choice.

So if your content is `hello"world` and your workflow has `foo: "${{ content }}"`, the script will be received as `foo: "hello"world"`.

**Comment by TWiStErRob** [comment]
Anyone fighting with this in the future, https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging or the equivalent "Enable debug logging" at https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs helps to see what the end result of the substitutions was.
