### ISSUE TITLE
Cannot use `core` in script

### ISSUE THREAD

**Issue by alexbde** [actions/github-script#10]
I want to let my github-script step fail (because an exception appeared). Is this somehow possible?

I tried to return a non-zero exit code via `return 42` but that only writes `42` to output variable `result`.

I tried to use `core.setFailed('message')` as in [GitHub example code](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-javascript-action#write-the-action-code) but it failed with `ReferenceError: core is not defined`.

I tried defining `core` using `const core = require('@actions/core')` but it failed with `ReferenceError: require is not defined`.

As there is already issue #6 stating `require` cannot be used I tried workaround described there (adding `const require = global.require || global.process.mainModule.constructor._load;` before code) but it failed with `Error: Cannot find module '@actions/core'`.

How can I let my step fail? Bonus points for letting it fail with a specified exit code.

Complete code I tried:

    script: |
      const require = global.require || global.process.mainModule.constructor._load
      const core = require('@actions/core')
      core.setFailed('message')
      return 42

**Comment by greenstatic** [comment]
Could you not just simply use `throw`? Example:
```js
script: |
  // Check for error
  if (true) {
    throw "This is an exception message."
  }
  // Everything is okay
  return 42;
```

**Comment by alexbde** [comment]
Haven't thought of that. Simple and straight forward 👍 Thank you!

**Comment by Simran-B** [comment]
Using v3 of this action also allows you to do this now:

```
- uses: actions/github-script@v3
  with:
    script: |
      core.setFailed('Action failed')
```
