### ISSUE TITLE
github.orgs.checkMembership is not a function

### ISSUE THREAD

**Issue by op-ct** [actions/github-script#101]
```
TypeError: github.orgs.checkMembership is not a function
```
https://octokit.github.io/rest.js/v17#orgs-check-membership

**Comment by jclem** [comment]
This is likely due to a semi-outdated Octokit package. We update Octokit periodically, but if anything's been added in the last week or so, gitHub-script won't have it, yet.

**Comment by andrewsomething** [comment]
In v18.x.x `checkMembership` was renamed to `checkMembershipForUser`

```
octokit.orgs.checkMembershipForUser({
  org,
  username,
});
```

https://octokit.github.io/rest.js/v18#orgs-check-membership-for-user

From the changelog:

> octokit.orgs.checkMembership() has been renamed to octokit.orgs.checkMembershipForUser()

https://github.com/octokit/rest.js/releases/tag/v18.0.0

**Comment by op-ct** [comment]
:+1: Thanks @jclem and @andrewsomething
