### ISSUE TITLE
Get branch on context object.

### ISSUE THREAD

**Issue by Milo123459** [actions/github-script#103]
**Is your feature request related to a problem? Please describe.**
I need to get the branch that triggered the event, ie context.branch
**Describe the solution you'd like**
For instance, dependabot making a PR, I have a script to git-checkout to it but I need to get the branch.
**Describe alternatives you've considered**

**Additional context**

**Comment by Milo123459** [comment]
@jclem Is this already added? Is there another way to get it?

**Comment by jclem** [comment]
@Milo123459 Can you please fill out the questions in the issue template? I unfortunately don't understand what exactly it is you're asking, I'm sorry!

**Comment by Milo123459** [comment]
> @Milo123459 Can you please fill out the questions in the issue template? I unfortunately don't understand what exactly it is you're asking, I'm sorry!

Sorry for the late response,I just want something like context.branch that tells you the branch name from a PR

**Comment by huonw** [comment]
More generally, it appears there's various properties available on `github` for YAML substitution, that aren't available on `context` in `github-script`: comparing https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context and https://github.com/actions/toolkit/blob/main/packages/github/src/context.ts this includes:

- `action`
- `action_path`
- `actor`
- `base_ref`
- `head_ref`
- `workflow`
- `workspace`

As a work-around, I think these are available as `process.env.GITHUB_...`: https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables. (This issue may be better suited to the https://github.com/actions/toolkit repo, and overlaps with, for instance, https://github.com/actions/toolkit/issues/555)

**Comment by jclem** [comment]
Yeah that's correct. I don't plan on keeping that object in sync with what Actions calls the "GitHub context". Same word, but I'm using it to refer to something else. You can use YAML substitution in your script value in the config file, or as you say pull values out of the environment.
