### ISSUE TITLE
Enrich context object with job, step, output objects

### ISSUE THREAD

**Issue by wbrefvem** [actions/github-script#114]
**Is your feature request related to a problem? Please describe.**
I would like to reference the output of another step from within a script.

**Describe the solution you'd like**
It would be nice if the context object were richer, including things like jobs, steps, ouputs, etc.

**Describe alternatives you've considered**
I've considered writing the output to a file or storing it in an environment variable.

**Additional context**
I'm trying to add additional build meta to a helm chart's version (in context it's only necessary to understand that the version has to be semver), but I want to base it on the current chart's version. This means reading in the current chart version from a YAML file, then appending things like a branch name, a Jira id, and a commit hash to the prelease and build portions of the version string. Currently I'm using `yq` to parse the version from the yaml file, adding the releveant meta, and then storing it in a step output that i'm referencing from a few other steps. I want to be able to comment on a PR with this version string so that developers and QE engineers can deploy the chart to relevant environments.

**Comment by joshmgross** [comment]
Thanks for the suggestion @wbrefvem.

The `context` object included in this action is from the `@actions/github` package, could you file an issue in https://github.com/actions/toolkit/issues for any changes you'd like made to that package?
