### ISSUE TITLE
github.checks.create fails when using `github-token`

### ISSUE THREAD

**Issue by polarclair** [actions/github-script#118]
**Describe the bug**
Script that uses:

```
     - name: Block merge
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Changes detected",
              head_sha: context.sha,
              conclusion: "action_required",
              details_url: context.payload.repository.url + "/actions/runs/" + context.runId,
            }) 
```
Is failing for `Unhandled error: HttpError: You must authenticate via a GitHub App.`.

**To Reproduce**
1. Create a workflow with the above action
2. Create a PR for branch
3. replace github-token for your env

**Expected behavior**
This should create a check run called "Changes detected".

**Additional context**
The check works fine under github-actions bot if you remove the github-token line even though the PAT supplied has admin permissions.

**Comment by joshmgross** [comment]
👋  The Checks API is only available to GitHub Apps, so you'd need to use a separate GitHub App token rather than a PAT if you wanted to replace `github-token` for any Checks API calls.

See https://docs.github.com/en/rest/reference/checks for more info.
