### ISSUE TITLE
CHANGELOG / breaking changes in 3.0

### ISSUE THREAD

**Issue by SleeplessByte** [actions/github-script#119]
Via dependabot I received updates to bump the version of `github-script`. In fact, it also provides [this compare view](https://github.com/actions/github-script/compare/6e5ee1dc1cb3740e5e5e76ad668e3f526edbfe45...47f7cf65b5ced0830a325f705cad64f2f58dddf7).

I've tried to look for CHANGELOD.md, MIGRATING.md, or a release tag with information on what was breaking, but it's not straightforward to figure out.

1. Can someone help me with telling me what the breaking changes are, or doesn't this action follow semver?
2. Is it perhaps an idea to keep a CHANGELOG.md?

**Comment by joshmgross** [comment]
From https://github.com/actions/github-script/releases/tag/v3.0.0
>The Actions and Octokit dependencies have been bumped. Since they contain major version updates, this also constitutes a major version update for this action

Does Dependabot not show the release notes?

**Comment by SleeplessByte** [comment]
Nope, but I think GitHub must have been shitting the bad, because the releases tab was also empty (when I posted this issue). I can see it now, so as far as I'm concerned, using releases is perfectly fine 🥇
