### ISSUE TITLE
Can I use secrets.GITHUB_TOKEN?

### ISSUE THREAD

**Issue by imbsky** [actions/github-script#12]
Can I use

```yml
github-token: ${{ secrets.GITHUB_TOKEN }}
```

instead of

```yml
github-token: ${{ github.token }}
```

**Comment by jclem** [comment]
Yes! In fact, the recommended syntax is to use `secrets.GITHUB_TOKEN`. I believe `github.token` is still around mostly for historical reasons, so the recommended way of getting it is `secrets.GITHUB_TOKEN`. 

Thank you for the reminder to update the README!

**Comment by imbsky** [comment]
Cool!

**Comment by jclem** [comment]
Updated in https://github.com/actions/github-script/commit/87914af5096b4a69e535962bdb6e9a0862eb0cde

**Comment by imbsky** [comment]
👏

**Comment by imbsky** [comment]
`secrets.GITHUB_TOKEN` doesn't seem to work. We still need our own access token.
