### ISSUE TITLE
Error: Input required and not supplied: github-token

### ISSUE THREAD

**Issue by Xunnamius** [actions/github-script#122]
**Describe the bug**

[`Error: Unhandled error: Error: Input required and not supplied: github-token`](https://github.com/Xunnamius/projector-lens-lib-cjs/runs/2063587946?check_suite_focus=true).

Around a week ago, I noticed my auto-merge jobs failing in this way when attempting to merge PRs from dependabot. I assume it's because the repository secret is not being passed to the workflow for some reason, even though I have the line [`github-token: ${{ secrets.GH_TOKEN }}`](https://github.com/Xunnamius/projector-lens-lib-cjs/blob/55555edc5f05e9399dad0fa227cf4cfbe1169500/.github/workflows/build-test-deploy.yml#L756).

This behavior is strange since nothing about the workflow file has changed for several weeks, only dependencies (including actions like `github-script` and `checkout`) have been updated automatically by dependabot.

~~To work around this for now, I'll see if I can get away with using the default token instead of passing one manually.~~ Nope.

**To Reproduce**
1. Use `github-scripts` and `github-token: ${{ secrets.GH_TOKEN }}` in a workflow step triggered by a PR on a contributor's branch (i.e. dependabot)
2. Aforesaid error occurs

**Expected behavior**
Everything continues to work as it did before a week ago, or some guidance on what changed/how to fix it :)

**Additional context**
Others might be experiencing [the same problem using other actions](https://github.com/actions/checkout/issues/298#issuecomment-795542242), which might make it an Octokit/GitHub issue?

It's also happening across my [others repos](https://github.com/Xunnamius/git-add-then-commit) [that use](https://github.com/Xunnamius/next-test-api-route-handler) [this action](https://github.com/Xunnamius/projector-lens-cli/actions).

**Comment by case** [comment]
We've been looking into this as well, and are thinking it might be related to the recent security issue: 

https://github.blog/2021-03-08-github-security-update-a-bug-related-to-handling-of-authenticated-sessions/

**Comment by Xunnamius** [comment]
Turns out this change was mode on purpose (and I guess I'll need to follow the GitHub blog more closely these days): https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
