### ISSUE TITLE
Error: Unhandled error: SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by yi-Xu-0100** [actions/github-script#123]
**Describe the bug**

Error: Unhandled error: SyntaxError: Invalid or unexpected token

**To Reproduce**

```bash

Run actions/github-script@v3.1.0
  with:
    script: await github.pulls.create({
    owner: context.repo.owner,
    repo: context.repo.repo,
    head: prepare-release,
    base: main,
    title: 'chore(release): :bookmark: release v1.0.4',
    body: '
  ### Bug Fixes
  
  - **actions:** 🐛 fix not found branch ([25b4e19](https://github.com/yi-Xu-0100/test/commit/25b4e1926a26dca753a2b6bb8627881f47941428))
  - fix push error ([62458bf](https://github.com/yi-Xu-0100/test/commit/62458bf2fede7fe842cd9176cec6920a339469d8))',
    maintainer_can_modify: true,
  })
  
    github-token: ***
    debug: false
    user-agent: actions/github-script
    result-encoding: json
  env:
    BASE_BRANCH: main
    HEAD_BRANCH: prepare-release
SyntaxError: Invalid or unexpected token
    at new AsyncFunction (<anonymous>)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:5368:56)
Error: Unhandled error: SyntaxError: Invalid or unexpected token
    at main (/home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:5394:26)
    at Module.720 (/home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:5378:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:52:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

https://github.com/yi-Xu-0100/test/runs/2104771640

**Comment by yi-Xu-0100** [comment]
I use the personal access token with repo permission, It also failed.

https://github.com/yi-Xu-0100/test/runs/2105106871

I also try the token locally, with the same code of the `github-script`, it is doing well. I do not know the reason for the error happening.

**Comment by joshmgross** [comment]
👋  @yi-Xu-0100 was this a previously working workflow that recently started failing? Or have you been consistently seeing these errors?

**Comment by yi-Xu-0100** [comment]
@joshmgross Thanks for your reply! Before this works, I did not use the `github-scripts` to do the workflows about creating a PR. I test again and get the error again even I use the `try...catch`. See in [workflows about `github-script`](https://github.com/yi-Xu-0100/test/runs/2155006198). 😥

By the way, I use `github-script` well in doing the workflows about the issue even the issue is a PR. See in [workflow about PR comment](https://github.com/yi-Xu-0100/vscode-conventional-commits/actions/runs/670569546/workflow). 👀

**Comment by TiKevin83** [comment]
An action experiencing this issue last worked for us on 3/8 and began failing on 3/10. Experiencing the same behavior where act can run the script fine locally with the token hardcoded, but the same script run automatically in GitHub Actions can't pull the token from secrets.

**Comment by yi-Xu-0100** [comment]
@joshmgross I don't know why, but it works fine at this time(v3.1.1). Even the v3.1.0 works fine also. 😅

If you don’t need to track this issue, just close it without asking. 😊

**Comment by TiKevin83** [comment]
thanks for pointing out that article, the change between the pull_request and pull_request_target events was what was affecting us
