### ISSUE TITLE
`details_url` does not work for `github.checks.create`

### ISSUE THREAD

**Issue by mayank99** [actions/github-script#143]
**Describe the bug**
When creating a check run, passing a custom url to [`details_url`](https://docs.github.com/en/rest/reference/checks#:~:text=commit-,details_url,-string) seems to do nothing. (The link stays same)

**To Reproduce**
From workflow file:
```
- name: Create check run
  uses: actions/github-script@v4
  with:
    script: |
      github.checks.create({
        owner: context.repo.owner,
        repo: context.repo.repo,
        head_sha: '${{ github.event.pull_request.head.sha }}',
        conclusion: '${{ job.status }}',
        name: 'Test results',
        details_url: "CUSTOM_URL",
        output: { "summary": "See test results at CUSTOM_URL" }
      })
```

**Expected behavior**

The url passed should be reflected in the "Details" link. (Right now it just takes you to the Checks tab, same as if the param was not passed)

![image](https://user-images.githubusercontent.com/9084735/118508030-cc44b200-b6fc-11eb-8d9a-128f4daa8ec8.png)

**Additional context**

Trying to google the problem I came across this: https://github.community/t/checks-api-creating-new-check-run-can-not-set-details-url/152651

Makes me wonder if this is a bug in the API itself.

**Comment by mayank99** [comment]
Update: I think in my use case, creating a "Check" might be unnecessary, so I've decided to instead create a "Status" using [`github.repos.createCommitStatus`](https://octokit.github.io/rest.js/v18#repos-create-commit-status). The "Details" link can be controlled using `target_url` and it works great. 🎉

**Comment by air3ijai** [comment]
Probably it could be related to the `GITHUB_TOKEN`?

[Create a check run, details_url is not being set #26757](https://github.com/orgs/community/discussions/26757)
> We don’t support showing a `details_url` for check runs created with the Actions `GITHUB_TOKEN`.
>
> If you want this scenario to work, you’d need to use a different token from a GitHub App.
