### ISSUE TITLE
"Welcome first time contributors" - usage example broken

### ISSUE THREAD

**Issue by vraravam** [actions/github-script#149]
**Describe the bug**
The example code was copied from the main `README.md` - to welcome the first time contributors.

**To Reproduce**
1. https://github.com/getferdi/recipes/blob/master/.github/workflows/first-time-contributor.yml

**Expected behavior**

**Screenshots**
<img width="1363" alt="Screen Shot 2021-06-04 at 6 57 50 PM" src="https://user-images.githubusercontent.com/69629/120808519-aca0ec80-c538-11eb-95af-d80ed70dddb6.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Simran-B** [comment]
The example in `README.md` is not broken. You modified this part:

```diff
-body: 'Welcome, new contributor!'
+body: 'Welcome, ${{ creator }}! Thanks for contributing to Ferdi!'
```

It looks like you try to use a GitHub Actions expression to construct the string in JavaScript. What happens is that the expression is evaluated before this whole step is executed. There is no `creator` context, as the error message correctly states:
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts

What you probably meant to do is to use JavaScript string interpolation:

```js
body: `Welcome, ${ creator }! Thanks for contributing to Ferdi!`
```

Note that the string is wrapped in backticks and that there's only a single curly brace on each side of the inline expression.

**Comment by vraravam** [comment]
thanks @Simran-B - I have made the appropriate changes in my repo.
