### ISSUE TITLE
Trying to associate an issue to a project, but the action fail

### ISSUE THREAD

**Issue by nuwanbando** [actions/github-script#16]
My workflow is at - https://github.com/nuwanbando/cnip-catalog/blob/master/.github/workflows/main.yml

I get following error - https://github.com/nuwanbando/cnip-catalog/commit/a4c0a4764d14f81ed34a10db1aa8fdd207fa840c/checks?check_suite_id=365671087

```js
errors: [
    {
      resource: 'ProjectCard',
      code: 'unprocessable',
      field: 'data',
      message: "Could not resolve to a node with the global id of 'MDU6aXNzdWU5'."
    }
  ]
```

**Comment by jclem** [comment]
@nuwanbando Double-check the "Parameters" described [here](https://developer.github.com/v3/projects/cards/#parameters-1) for that endpoint. I don't believe you need to be passing in the `...context.issue`. That endpoint only takes `note`, `content_id`, and `content_type` (which I think should be "Issue" (title-case), not "issue").

Let me know if just removing that `...context.issue` and title-casing the content type doesn't solve the problem for you!

**Comment by jclem** [comment]
Going to close this, but please reopen if my above suggestion doesn't help.
