### ISSUE TITLE
Support importing ESM files

### ISSUE THREAD

**Issue by JamesMGreene** [actions/github-script#168]
**Is your feature request related to a problem? Please describe.**

This Action recently [added](https://github.com/actions/github-script/pull/135) [support](https://github.com/actions/github-script/pull/136) for importing CommonJS-based npm packages and local modules within the `script` body using an monkey-patched `require(...)` method. That is awesome! 🎉 

Alas, the Node.js community has been moving away from CommonJS more and more now that the ECMAScript Modules (ESM) standard is out of its experimental status.

The good news? If your module/application is written with ESM, it can import both other ESM files _**and**_ CommonJS modules using the new `import` keyword, or a dynamic `import(...)` method call. 💚 

```js
// Syntax-sugared import statements
import { has } from 'lodash-es'  // An ESM package
import { getOctokit } from '@actions/github'  // A CommonJS package

// Dynamic import method call
const { setOutput } = await import('@actions/core')  // A CommonJS package
```

The bad news? If your module/application is written with CommonJS, the `require(...)` method can _**only**_ import other CommonJS modules. It is _**not**_ possible to directly import ESM files because they are not guaranteed to be synchronous, which is a requirement of the `require(...)` approach. The `import` keyword is not available within CommonJS files _but_ it is possible to use the dynamic `import(...)` approach instead. However, the `import` method is not currently accessible within `github-script` blocks &mdash; I tried that and it failed! ❌ 

Unfortunately, this means that I can no longer utilize this Action's handy `require(...)` behavior on my own application's local modules as we recently converted to ESM (after becoming blocked by a dependency that converted to ESM 😬), e.g. [`github/docs`@`.github/workflows/staging-deploy-pr.yml#L52-L61`](https://github.com/github/docs/blob/fd770f371c87ae1a8570f3914cfbd45bd23d15ef/.github/workflows/staging-deploy-pr.yml#L52-L61) 😭 

**Describe the solution you'd like**

In an ideal world, I think we probably should have _only_ added support for the ESM approach to this module such that we could've supported both. Alas, timing and knowledge such as they were, we opted for the standard CommonJS `require(...)` approach.

Unfortunately, this would prevent us from adding full support for ESM's `import` keyword now, or at least not without at least [bumping this Action's **major** version number](https://semver.org/) to indicate the breaking change.

As such, I think a more reasonable compromise would be to just add support for the dynamic `import(...)` method calls within the current wrapping function.

**Describe alternatives you've considered**

I did some fairly extensive testing of a handful of approaches and potential workarounds to this situation:

&nbsp; &nbsp; <img alt="Workflow job statuses" src="https://user-images.githubusercontent.com/417751/125863995-a4d902b6-a736-4154-9a13-13a4d5a714f0.png" width="300" />

You can see the implementation details in [this workflow file](https://gist.github.com/JamesMGreene/774b210bccbb547aefa64991c1555712).

The failed job above ☝🏻 that I would like to see passing with the proposed solution is the **"Try ESM dynamic imports"** (`esm-dynamic-imports`) job.

_Alternative (1):_

I was only able to get 1 of the 6 attempts working with the current state of the `github-script` Action, which involves using the `esm` npm package and some questionable additional workarounds that may or may not work when applied to more advanced ESM dependency chains. 🤷🏻‍♂️ 

_Alternative (2):_

Not use `actions/github-script` and just run a roughly equivalent Node.js script that uses `@actions/core`, etc. 😢  

**Additional context**

N/A 🤷🏻‍♂️

**Comment by LongLiveCHIEF** [comment]
commenting to prevent auto-removal.

Will this be resolved when node 16 goes LTS?  (not sure what github actions will be doing with node on Ubunut runners)

**Comment by JamesMGreene** [comment]
@ethomson 

> I think that if we update `actions/github-script` in a new major version to use the node16 runner that this may "just work"?

This would be awesome but it may be wishful thinking. 😅  When this action was updated to support `require` for local/installed modules, it needed some tricky patching to utilize the correct paths. 🤔

**Comment by JamesMGreene** [comment]
JavaScript Actions can now run using Node.js 16 by changing the `action.yml` file's `runs.using` configuration from `using: node12` to `using: node16`: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-nodejs-v16

I imagine this means we can now investigate if switching to `using: node16` makes ESM imports possible -- at least via the dynamic `import(...)` function. 🙃

**Comment by joshmgross** [comment]
With #235 and `actions/github-script` using Node 16, it looks like this should Just Work™️

https://github.com/joshmgross/actions-testing/runs/5130290014?check_suite_focus=true

Workflow:
```yaml
      - uses: thboop/github-script@d2ed94b14f4e194b2afdd7fe2af49e0d93c42d92
        with:
          script: |
            try {
              console.log('Before dynamic import')
              const { default: printStuff } = await import('${{ github.workspace }}/src/print-stuff.js')
              console.log('After dynamic import')
              await printStuff()
              console.log('At the end')
            } catch (error) {
              console.error('Threw an error!')
              throw error
            }
```

`package.json`
```json
{
   "name": "",
  "description": "",
  "type": "module",
  "private": true,
  "version": "0.1.0",
  "dependencies": {},
  "devDependencies": {}
}
```

`src/print-stuff.js`
```js
export default function printStuff() { console.log('stuff') }
```

Since we're not wrapping `import` like we are with `require` (#135), I'm not sure how it would work with installed NPM modules and we need to specify the full absolute path using the workspace variable `await import('${{ github.workspace }}/src/print-stuff.js')`

**Comment by meteor-vladimir573** [comment]
Explore this answer



https://trespasserpromiscuous10.github.io/rL9QcYj6675R2cKEuuT0Xcv_bHkGF85dTp61tTtavwfYyu_NF4F5cTWYknRCPaIVdHWx_Q/
