### ISSUE TITLE
Secrets are not masked in comment

### ISSUE THREAD

**Issue by bahag-welscha** [actions/github-script#180]
**Describe the bug**
I'm using actions/github-script@v4.0.2 to add a comment to an pull request. 
The body of the pull-request contains stdout output of a step before. When logging the stdout output the secrets are masked but when using the same stdout in the body of the comment then the secrets are not masked anymore.

**To Reproduce**
1. Use an env with a value from {{ secrets.<YOUR_SECRET_KEY> }}
2. Log the value to stdout
3. (Optional) Log stdout to verify that the value is masked
4. use github.issues.createComment({body: my-string-which-contains-stdout-output})

**Expected behavior**
I would expect to have a masked value in the created comment instead of the real value

**Screenshots**
Output in Github Action
![image](https://user-images.githubusercontent.com/86712126/130042405-337a5f7e-593a-460c-b2a1-982e7eba3470.png)

Comment which was added
![image](https://user-images.githubusercontent.com/86712126/130042492-f8b044e2-9210-4ff0-b016-f82eefcc0b52.png)

**Desktop:**
 - OS: [Github-Actions runner: ubuntu-latest]

**Additional context**
````
- name: Update Pull Request
  uses: actions/github-script@v4.0.2
  if: github.event_name == 'pull_request'
  env:
    PLAN: "Terraform\n${{ steps.plan.outputs.stdout }}"
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |

      console.log(process.env.PLAN) // here the value is masked

      const output = `
      #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
      #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
      #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

      <details><summary>Show Plan</summary>

      \`\`\`\`
      ${process.env.PLAN}
      \`\`\`\`
      </details>

      #### Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`
      `
      github.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: output
      })
````

**Comment by joshmgross** [comment]
👋  Hey @bahag-welscha,

Secret masking is specifically only done in Actions logs by the [Actions Runner](https://github.com/actions/runner). What you do with that secret and where you send it is entirely up to your own code. 

If you don't want it to appear in an issue comment, then I'd recommend filtering it out before creating the comment.
