### ISSUE TITLE
Security implications of running separate script file on pull request

### ISSUE THREAD

**Issue by Marcono1234** [actions/github-script#184]
Hello,
what are the security implications of running a separate script file (as [described in the README](https://github.com/actions/github-script#run-a-separate-file)) with a `pull_request` workflow trigger?

I assume this is something you should avoid because an adversary could in their pull request replace the script file and run arbitrary code. Is this assumption correct?
If so, it might be good to add a warning to the examples in the README to prevent users from creating vulnerable workflows (if you want I can create a pull request).

**Comment by joshmgross** [comment]
👋  Hey @Marcono1234,

The security implications are the same for running any untrusted code from `pull_request` events (such as public forks). This could be a separate script file using this action or just installing dependencies and building code.

Note that by default, `pull_requests` from forks have a read-only token and do not have access to any secrets, so the security vulnerability there is limited unless you're using self-hosted runners (which is not recommended for public repos).

I don't want to duplicate any guidance that we already have in our docs in this repository, as it could go stale and this isn't the best place for that information.

https://docs.github.com/en/actions/security-guides/automatic-token-authentication
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by Marcono1234** [comment]
Thanks a lot for this extensive answer and the links! I confused myself when I created pull requests against my own repository with workflows for creating comments, and therefore incorrectly assumed that `github-script` somehow has extended permissions.
It now all makes sense; sorry for the confusion.
