### ISSUE TITLE
Missing documentation of Node.js runtime used

### ISSUE THREAD

**Issue by fredrikhr** [actions/github-script#185]
In order to be able to write scripts using this action it would be helpful if the readme documented which version of the node.js runtime was used, so that developers have a clear idea what API-set they can rely on working and test their code accordingly.

I suspect this uses a [JavaScript-style action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action), in which case it would be great to state that it relies on the node.js engine provided natively by GitHub actions (preferably with a link to GitHub actions documentation that states what engine is used currently).

**Comment by joshmgross** [comment]
👋  @fredrikhr that information can be found in the `action.yml` file - https://github.com/actions/github-script/blob/main/action.yml#L29-L31

I'll see if I can find documentation for which specific version of Node, but it should be the latest LTS version of Node 12

**Comment by fredrikhr** [comment]
@joshmgross that makes sense. Could we still write into the Readme (or something along those lines)? 

> This action uses the Node.js runtime natively provided by the GitHub Actions Runner, see <link to GitHub docs pages> for more information about JavaScript hosted actions. 

I think that would be sufficient for people to figure out what they need to know.

**Comment by joshmgross** [comment]
👋  @skirsten see https://github.com/actions/runner/issues/772

**Comment by joshmgross** [comment]
👋  The Node version will depend on the current runner version

The "Set up job" section of the Actions logs will say which runner version is being used:
```
Current runner version: '2.285.1'
```

That maps to a release/tag in the `actions/runner` repository.

If you check `src/Misc/externals.sh`, you can see which Node version is being used:

```sh
NODE12_VERSION="12.13.1"
```
https://github.com/actions/runner/blob/v2.285.1/src/Misc/externals.sh#L6
