### ISSUE TITLE
Unhandled error: SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by PatrickHeneise** [actions/github-script#194]
**Describe the bug**

```
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Invite
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GE_INVITE_TOKEN }}
          script: |
            try {
              await github.orgs.getMembershipForUser({
                org: context.repo.owner,
                username: context.payload.sender.login
              })
            } catch (err) {
              if (err.status === 404) {
                await github.orgs.createInvitation({
                  org: context.repo.owner,
                  invitee_id: context.payload.sender.id
                })
              }
            }
```

I tested the action in `act` and it worked fine. Also I can use `cURL` to create the invitation. But in my repo the Action fails with the error `Unhandled error: SyntaxError: Invalid or unexpected token`. If I remove `createInvitation`, everything works fine.

**To Reproduce**
1. Run action above

**Expected behavior**

This should work; no idea why there's an error in the Actions environment and the error is very generic.

**Comment by PatrickHeneise** [comment]
idk what changed, but suddenly the workflow runs 🤷🏼

**Comment by chrisjohnson00** [comment]
For anyone else who runs into this... I had a comment inside my `script` block which caused this error.
