### ISSUE TITLE
HttpError due to missing context info (`context.issue.number`)

### ISSUE THREAD

**Issue by JessicaS11** [actions/github-script#203]
**Describe the bug**
I'm trying to replicate [Binder's Example 1](https://mybinder.readthedocs.io/en/latest/howto/gh-actions-badges.html) to automatically add a Binder link to my repo when a PR is created. I'm getting an HttpError:
```RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:4614:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HttpError',
  status: 404,
  response: {
    url: 'https://api.github.com/repos/icesat2py/icepyx/issues//comments',
    status: 404,
...
```
I'm guessing this is tied to the "//" in the url, which I'm hypothesizing means that `context.issue.number` isn't being filled in properly (because it doesn't show up if I view `console.log(context)`).

**To Reproduce**
```
name: AddBinderBadge
on:
  push:
  pull_request_target:
    types: [opened]

jobs:
  add-badge:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on PR with Binder link
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log(context)
          var BRANCH_NAME = process.env.GITHUB_REF.replace("refs/heads", "");
          var CONTENT_REPO = process.env.CONTENT_REPO;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/${CONTENT_REPO}/${BRANCH_NAME}?labpath=examples) :point_left: Launch a binder notebook on this branch`
          })
      # NOTE: Setting the vars as env vars is required to make them available within the Comment on PR step
      env:
        GITHUB_REF: ${{ github.ref }}
        CONTENT_REPO: ${{ github.repository }}
```

**Expected behavior**
I expected to be able to automate adding a PR comment with the binder badge to my repo.

**Screenshots**
Here's the [log](https://github.com/icesat2py/icepyx/runs/3865046907?check_suite_focus=true) from running the action.

**Desktop (please complete the following information):**
 - Browser Firefox

**Additional context**
Despite several working examples, I've had no end of issues getting this up and running in my repo. One primary challenge was in getting the branch name for the PR, during debugging of which I determined that the github context was not being populated as I expected for a PR (see this [GitHub community post](https://github.community/t/output-of-github-event-pull-request-head-is-blank/205377)).

**Comment by JessicaS11** [comment]
I ultimately got a binder badge action working (using the [GitHub action](https://github.com/manics/action-binderbadge)), but I'd still be keen to know how to modify the posted example to get it to work as I try to build more of my own action workflows.

**Comment by riosje** [comment]
I have had the same issue it was beacase the action was being triggered by the push instead of the PR, so the context has missing the issue number, so I enforce the action to be triggered with the PR instead of the push.

**Comment by quulah** [comment]
I ended up here when trying to find a PR number in a case where the workflow was triggered by other means.

I came up with this, hopefully it'll help others even if it doesn't directly answer to the problem in this issue.

```
const issues = await github.rest.pulls.list({
  owner: context.repo.owner,
  repo: context.repo.repo,
  state: 'open',
  head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
})

const pr = context.issue.number || issues.data[0].number
```

And then use `pr`  as `issue_number` when calling `createComment()`.

**Comment by joshmgross** [comment]
```yaml
name: AddBinderBadge
on:
  push:
  pull_request_target:
    types: [opened]
```

If your workflow is triggering off of a `push` event, there won't be an associated issue in the context. I'd recommend removing that `push` trigger to get that example workflow working.
