### ISSUE TITLE
Unable to retrieve alternate media type via API requests

### ISSUE THREAD

**Issue by barunio** [actions/github-script#214]
**Describe the bug**
When making a request using the `github` pre-authenticate `octokit/rest.js` client, setting the [request format](https://octokit.github.io/rest.js/v18#request-formats-aborts) does not work properly. This is possibly because the `Accept` header has an incorrect version. Instead of a `v3` string in the version portion of the header, it sets a version of `-preview`, so the accept header string looks like `application/vnd.github.-preview.raw` instead of `application/vnd.github.v3.raw`. As a result, all requests to the API return results assuming the default media type.

**To Reproduce**

In a GitHub action, try using the `github` object at all and examine the request options.

Here's an example of a request to retrieve a raw formatted file that fails:

```
let requestOptions = github.rest.repos.getContent.endpoint({
  owner: context.repo.owner,
  repo: context.repo.repo,
  path: filename,
  ref: context.sha,
  mediaType: {
    format: 'raw'
  }
});

console.log(requestOptions)
```

This outputs:
```
{
  method: 'GET',
  url: # <URL>,
  headers: {
    accept: 'application/vnd.github.-preview.raw',
    'user-agent': 'actions/github-script octokit-core.js/3.5.1 Node.js/12.13.1 (linux; x64)'
  },
  ...
}
```

You can do this with any request to any endpoint, including those that do not specify a custom media type, and see that the `accept` string still sets `-preview` as the version.

One surprising thing when debugging: I tried manually setting `requestOptions.headers.accept` and it still did not return the appropriate media type. What I tried was:

```
let requestOptions = github.rest.repos.getContent.endpoint({
  owner: context.repo.owner,
  repo: context.repo.repo,
  path: filename,
  ref: context.sha,
  mediaType: {
    format: 'raw'
  }
});

requestOptions.headers.accept = 'application/vnd.github.v3.raw'
console.log(requestOptions)

await github.request(requestOptions)
```

**Comment by bojanpotocnik** [comment]
@barunio have you managed to solve this issue?

https://github.com/actions/github-script/issues/243 is a duplicate of this.
