### ISSUE TITLE
Provide the steps on the context

### ISSUE THREAD

**Issue by danielo515** [actions/github-script#233]
Before anything, thanks for this extension that makes easy run any code on actions

**Is your feature request related to a problem? Please describe.**
I want to be able to reference previous steps within my code. I see that extensions have the ability to[ access this information](https://docs.github.com/es/actions/learn-github-actions/contexts#steps-context), but seems that this action is not passing that down to the executed script on the context object.

**Describe the solution you'd like**
I want to be able to reference the steps-context within the code of the script

**Describe alternatives you've considered**
Currently I can pass the objects stringified to the script or other solutions, but this is cumbersome because you never know what you are going to get exactly and is specially inconvenient on external scripts

**Additional context**

**Comment by joshmgross** [comment]
Thanks for your feedback!
The context available in this action is passed from the `@actions/github` package, so I'd recommend filing an issue in the https://github.com/actions/toolkit repository.

If that support is added, we can bump the version of `@actions/github` used by this action.
