### ISSUE TITLE
"Error: not supported"

### ISSUE THREAD

**Issue by bennypowers** [actions/github-script#244]
**Describe the bug**
I wrote a workflow step using `actions/github-script@v5`. The action [requires a cjs script](https://github.com/patternfly/patternfly-elements/blob/5e5e21f4d8dd0a4244514047ae4723fa577d39f5/scripts/bundle-release.cjs), which is supposed to generate and upload artifacts to a github release. The [workflow](https://github.com/patternfly/patternfly-elements/actions/runs/1934538355/workflow) runs on release. The [workflow fails with `Error: not supported`](https://github.com/patternfly/patternfly-elements/runs/5424489741?check_suite_focus=true) on the line which imports a module from the a monorepo package in the repository.

**To Reproduce**
1. Run the above workflow

**Expected behavior**
importing the repository script succeeds, or provides a descriptive error message

**Comment by joshmgross** [comment]
Does your script work with `actions/github-script@v6`?

**Comment by bennypowers** [comment]
Yeah [looks good](https://github.com/patternfly/patternfly-elements/runs/5428581399?check_suite_focus=true).

Thank you and have a nice weekend
