### ISSUE TITLE
Formatting the text in the body

### ISSUE THREAD

**Issue by AshNaz87** [actions/github-script#247]
Hey folks! Awesome project you have here!

Just have a question regarding the `body` property when creating a comment.

Is it possible to format it? I.e. make it bold or apply some colour to the text?

This may be in the documentation, but I have not come across it. 

Many thanks!

**Comment by josh-** [comment]
You can use [Markdown formatting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) in the body:

```js
github.rest.issues.createComment({
  issue_number: context.issue.number,
  owner: context.repo.owner,
  repo: context.repo.repo,
  body: "**Bold text here**"
})
```

Note that if you have a multi-line comment that the indentation must be correct, otherwise your formatted text will be placed 
inside an intended code block. Example of correct indentation is:

```
github.rest.issues.createComment({
  issue_number: context.issue.number,
  owner: context.repo.owner,
  repo: context.repo.repo,
  body: `# Images

	# Title 
    ![](https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png)`
})
```

**Comment by AshNaz87** [comment]
Cheers @josh- 

I'll give this a spin. This really ought to be in the documentation

**Comment by AshNaz87** [comment]
Works like a charm! Cheers :)

**Comment by josh-** [comment]
You're welcome! Just opened #252 adding an example to the docs 👍

**Comment by kirillgroshkov** [comment]
> Note that if you have a multi-line comment that the indentation must be correct, otherwise your formatted text will be placed
inside an intended code block.

Indeed, my issue was a wrong indentation 👍

**Comment by amol-patel** [comment]
@josh- We denote code or a command within a sentence using single backticks. Could you please explain how to escape backticks when they're part of the text body?

**Comment by joshmgross** [comment]
@amol-patel you should be able to use a `\` to escape any backticks:

> To escape a backtick in a template literal, put a backslash (`\`) before the backtick.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by amol-patel** [comment]
Thank you so much @joshmgross
