### ISSUE TITLE
`github-token` cannot be found

### ISSUE THREAD

**Issue by BastianZim** [actions/github-script#248]
Hi everybody, 

I'm sure this is a very obvious fix but somehow I'm pulling my hair on this one.

We have a workflow that uses the `github-token` tag as we need a special token. This is provided here: https://github.com/conda-forge/staged-recipes/blob/8ab014a03d07b5d7fe6d269dc1d4f81cbd9886f0/.github/workflows/automate-review-labels.yml#L79

The token is provided using a secret with the following format: `${{ secrets.GH_TOKEN }}`

This token is also used in a different workflow where everything is working well: https://github.com/conda-forge/staged-recipes/blob/8ab014a03d07b5d7fe6d269dc1d4f81cbd9886f0/.github/workflows/create_feedstocks.yml#L58

Yet, somehow, our workflow fails with `Error: Input required and not supplied: github-token`. Logs: https://github.com/conda-forge/staged-recipes/runs/5543442584?check_suite_focus=true

Can anyone see why this might be happening?

**Comment by joshmgross** [comment]
Looking at that run https://github.com/conda-forge/staged-recipes/actions/runs/1982747329

```
Triggered via pull request review comment 22 hours ago
```

Was this a fork pull request? If so, we don't send secrets to runs for fork full requests - https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
