### ISSUE TITLE
CreateComment with certain urls in body string causes exception

### ISSUE THREAD

**Issue by pergardebrink** [actions/github-script#256]
**Describe the bug**
With certain body contents (issue urls), the request to github.rest.issues.createComment fails with `RequestError [HttpError]: invalid json response body at https://api.github.com/repos/<myorg>/<myrepo>/issues/<pullrequestnumber>/comments reason: Unexpected end of JSON input`

The bug appears only to happen if you add a url to an issue in another repository anywhere in the body. Putting a url to an issue in the same repository as the action itself seems to work, and also something like https://www.google.com will work.

Running the same client from @actions/github locally on nodejs with the exact same code in my example to create a comment works without a problem, so it seems to be related to either the GitHub Actions environment or the github-script action.

**To Reproduce**
1. Create a GitHub Action workflow containing the following code snippet:
    ``` 
    name: Pull Request bug
    
    on: 
      pull_request:
    
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Add Pull Request comment
            uses: actions/github-script@v6
            with:
              script: |
                const result = await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "https://github.com/github/docs/issues/16950"
                });
    ```
2. Create a pull request that will trigger the above workflow action

**Expected behavior**
A comment will appear on the pull request and the workflow will succeed

**Screenshots**
[
![actionsbug](https://user-images.githubusercontent.com/8502070/162566063-54ee3c5a-6ee6-49bb-bdc8-742221298c11.png)
](url)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by pergardebrink** [comment]
I have now been able to reproduce this issue outside of github-script and it seems that the issue is because of a bug in the GitHub api when using the token provided by GitHub Actions. I was able to reproduce the issue with this code: 
```
name: Pull Request bug

on: 
  pull_request:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deps
        run: |
          npm install node-fetch@2
      - name: Add Pull Request comment
        uses: actions/github-script@v6
        with:
          script: |
            const fetch = require('node-fetch');
            const url = "https://api.github.com/repos/<owner>/<repo>/issues/<issue_number>/comments";
            const token = '${{ secrets.GITHUB_TOKEN }}';

            const response = await fetch(url, {
              method: "POST",
              headers: {
                Authorization: "token " + token,
                Accept: "application/vnd.github.v3+json",
              },
              body: JSON.stringify({
                body: "test https://github.com/aws/aws-cdk/issues/1299",
              }),
            });

            console.log(response);
            const data = await response.text();
            console.log(data);

```

And got Internal Server Error (500) and an empty response body (which of course means it is invalid json with "unexpected end of JSON input")

![image](https://user-images.githubusercontent.com/8502070/162612779-0153343d-ccbe-4d5a-94f1-1a3341f444e5.png)

**Comment by lyschoening** [comment]
@pergardebrink We're having the same issue. Do you have a tracking link for that issue report with GitHub?

**Comment by WillBartee** [comment]
> Thanks @pergardebrink, I don't think there's anything for `actions/github-script` to fix here so I'm going to close this issue.
> 
> I'll follow up on that internal support ticket.

@joshmgross @pergardebrink Are there any external/public links for that issue? Possibly something on a roadmap?

**Comment by pergardebrink** [comment]
> > Thanks @pergardebrink, I don't think there's anything for `actions/github-script` to fix here so I'm going to close this issue.
> > I'll follow up on that internal support ticket.
> 
> @joshmgross @pergardebrink Are there any external/public links for that issue? Possibly something on a roadmap?

No, I only have a support ticket that apparently was closed in september by GitHub.ä with this as a last message:

> 
> Hi Per,
> 
> Sorry that this is taking a while.
> 
> I still don't have an update from Engineering about the fix (there needs to be some additional changes that might take a while to implement).
> 
> Would you consider a workaround for this? What am thinking here is to catch the 500 error exception and prevent the step creating the comment from failing in case you get this error code.
> 
> Regards,
> Paul
> GitHub Support

**Comment by joshmgross** [comment]
The engineering item tracking this issue is still open on the team's backlog.
