### ISSUE TITLE
Automatically turn on debugging

### ISSUE THREAD

**Issue by TWiStErRob** [actions/github-script#264]
I'm trying to debug a `script: |` block, and I have to modify the script with `debug: true` to be able to do so even though there's [UI for it](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs) in shape of "[x] Enable debug logging".

**Describe the solution you'd like**
Make the default value of `debug` param

https://github.com/actions/github-script/blob/7a5c598405937d486b0331594b5da2b14db670da/action.yml#L15-L17

equivalent to `default: ${{ secrets.ACTIONS_STEP_DEBUG || false }}`. Not sure if this would work verbatum, but what would work best if it tries to read the secret, and if that fails or not set, then falls back to the now-default `false`. I tried this as a parameter to the action, and it works well.

**Describe alternatives you've considered**
Trying to remember to put `debug: ${{ secrets.ACTIONS_STEP_DEBUG || false }}` for all of my .yml files.

**Additional context**
See https://github.com/TWiStErRob/github-actions-test/pull/1 for the workaround.

Normal run without debugging: https://github.com/TWiStErRob/github-actions-test/runs/6740560658
Re-ran with Enable debug logging: https://github.com/TWiStErRob/github-actions-test/runs/6740567848

Note: ignore the fact that there's no output, reported that separately https://github.com/actions/github-script/issues/265

**Comment by TWiStErRob** [comment]
@DanRigby @mjpieters now that debug actually does something, what are your thoughts on this?

**Comment by mjpieters** [comment]
I kind-of like this idea, it makes sense.

You can always use `debug: false` if you don't like the request logs from appearing when you enable debug logging, and `debug: true` if you want it enabled permanently.

**Comment by joshmgross** [comment]
Something like this should work with the existing "Enable debug logging" option:

```ts
const debug = core.getBooleanInput('debug') || core.isDebug()
```

**Comment by TWiStErRob** [comment]
> You can always use debug: false if you don't like the request logs from appearing when you enable debug logging, and debug: true if you want it enabled permanently.

@mjpieters Is my reading correct that you meant that the default makes sense in line with the UI checkbox, and if someone wants a different 'static' behavior, they can use what you described. i.e. "You can" = "If someone wants".

**Comment by TWiStErRob** [comment]
@joshmgross that wouldn't allow explicit `debug: false` to always turn it off, right?

**Comment by joshmgross** [comment]
> that wouldn't allow explicit `debug: false` to always turn it off, regardless of debug flag, right?

Good point, we'd need to check if it's set first:
```ts
  const debugSpecified = core.getInput('debug') !== ''
  const debug = debugSpecified ? core.getBooleanInput('debug') : core.isDebug()
```

**Comment by TWiStErRob** [comment]
... and that implies changing the default to '', I guess, because GHA or core would automatically fill the value in?

This looks like a viable -2+3 PR already :)

**Comment by mjpieters** [comment]
> ... and that implies changing the default to `''` (meaning "smart"), I guess, because GHA or core would automatically fill the value in?

`core.getInput()` returns a string, always, and so `''` is the value that you get when `debug` is not set (and there is no default value set in `action.yml`).

**Comment by TWiStErRob** [comment]
> core.getInput() returns a string, always, and so '' is the value that you get when debug is not set

Yep, that's what I'm thinking too...

> and there is no default value set in action.yml

... but there's a default right now:

https://github.com/actions/github-script/blob/8d76c9a9134fecb44ef7d530c839da2d1974d0bb/action.yml#L15-L17

**Comment by mjpieters** [comment]
However, you can use Github Action expressions as the default in `actions.yml`, so `${{ env.RUNNER_DEBUG || 'false' }}` should work just fine.

**Comment by mjpieters** [comment]
Correction: `RUNNER_DEBUG` is either absent (empty) or set to `'1'`, but `getBooleanInput()` looks for `true` or `false` (in various capitalisations), so the expression I gave is wrong. This should work better:

```yaml
  default: ${{ (env.RUNNER_DEBUG == '1' && 'true') || 'false' }}
```

**Comment by mjpieters** [comment]
I've confirmed locally (via https://github.com/nektos/act) that the above expression works as designed.

**Comment by TWiStErRob** [comment]
Does runner_debug take the secrets into account?

**Comment by mjpieters** [comment]
> Does runner_debug take the secrets into account?

The `ACTIONS_STEP_DEBUG` secret triggers debug mode but when triggered the runner [sets the `RUNNER_DEBUG` environment variable](https://github.com/actions/runner/pull/253).

Testing for the environment variable is also [what `core.isDebug()` does](https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/core/src/core.ts#L233-L235).
