### ISSUE TITLE
debug: true does nothing.

### ISSUE THREAD

**Issue by TWiStErRob** [actions/github-script#265]
**Describe the bug**
debug: true does nothing.

**To Reproduce**
1. Normal run without debugging: https://github.com/TWiStErRob/github-actions-test/runs/6740560658
2. `debug: false`, all good
3. Re-ran with Enable debug logging (see also https://github.com/actions/github-script/issues/264): https://github.com/TWiStErRob/github-actions-test/runs/6740567848
4. `debug: true`, but nothing output

---

I also tried without accessing the secret, hardcoding it too many times, but nothing.
Here's example: https://github.com/TWiStErRob/net.twisterrob.sun/pull/91/commits/33b74f6fe5c51167c7b46b3c8ab7505a2df487a2
See the "Publish "Gradle" result and Build Scan URL." step right after the [failure](https://github.com/TWiStErRob/net.twisterrob.sun/runs/6740341417?check_suite_focus=true).

**Expected behavior**
As documented
https://github.com/actions/github-script/blob/7a5c598405937d486b0331594b5da2b14db670da/action.yml#L16

**Screenshots**
`debug: false`
![image](https://user-images.githubusercontent.com/2906988/172024664-27b38f46-94a1-43ba-bc04-bd669d36697d.png)]

`debug: true`
![image](https://user-images.githubusercontent.com/2906988/172024688-21c24b50-4c23-4e31-bd2a-ebe289eb6a42.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version latest

**Additional context**
I have a repo where the code shown in the example doesn't create a commit status, and trying to debug it. Without `debug: true` working, I'm giving up.

**Comment by mjpieters** [comment]
The plugin correctly configures octokit, but **nothing in the current plugin list uses logging** (other than warnings, which are not affected by the debug flag).

Probably the easiest way to make it actually do anything with logging is to also add the [`@octokit/plugin-request-log` plugin](https://github.com/octokit/plugin-request-log.js).

**Comment by TWiStErRob** [comment]
Amazing @mjpieters, thanks!
