### ISSUE TITLE
Unable to use v6, to create comment on issue

### ISSUE THREAD

**Issue by lakshmajee** [actions/github-script#273]
**Describe the bug**
- [ ] When a request is made to create a comment, the step throw below error
```bash
Unhandled error: HttpError: Not Found
```
- [ ] Another problem is the library adds an additional slash before the resource
     ```js
       // should not have extras slash before `comments`
       https://api.github.com/repos/awkward-minion/gh_actions_poc/issues//comments
     ```

**To Reproduce**

1. Create a workflow file
2. use `github-script@v6` action
3. Add some code to create a comment
> Notes: Not provided any inputs apart from the script (assuming GitHub-script uses default token).

**Expected behavior**
- [ ] Should be able to create a comment using this action
- [ ] Should not add the extras slash in the request URL

**Screenshots**
https://github.com/awkward-minion/gh_actions_poc/runs/7257014713?check_suite_focus=true
![image](https://user-images.githubusercontent.com/15211916/178057664-54334140-6d72-4f93-b34f-580edbf07e33.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.24
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]:  95.0.4638.69 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
Repository available [here](https://github.com/awkward-minion/gh_actions_poc)
PS: I have added some random messages in the commit, please ignore them

**Comment by Tom-Whi** [comment]
I've noticed the same issue with the double slashes.

![image](https://user-images.githubusercontent.com/19737487/178581103-bfd9588f-72a7-4556-9f42-6567785f94fe.png)

**Comment by Tom-Whi** [comment]
Yep. I was agreeing with you.

I also have the same issue using @v5, which produces the same results.

**Comment by Tom-Whi** [comment]
Sadly not yet. I'm still trying find a workaround. If I find something I'll post back to this issue.

**Comment by Tomasz-Kluczkowski** [comment]
Thx a lot, indeed on push I inspected context and it was missing the issue number.

I have found a workaround though by getting the pull request number using another query.

On 15 Jul 2022, at 09:29, Awkward Minion ***@***.***> wrote:

﻿

Ok so this action is basically broken for now? To me it looks like it does not insert issue number when trying to create a comment?

request: {
    method: 'POST',
    url: 'https://api.github.com/repos/flexciton/azure_infrastructure_costs/issues//comments',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit-core.js/3.5.1 Node.js/16.13.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },


url: 'https://api.github.com/repos/flexciton/azure_infrastructure_costs/issues/ <HERE SHOULD BE ISSUE NUMBER?> /comments',

Yes exactly, because it won't be available on regular push events on the actions.
For now I am using pull_request event to deal with this (it automatically pick the issue from PR)

**Comment by infa-msheik** [comment]
> 

Hi @Tomasz-Kluczkowski 

Can you please let me know the query you used to get the pull request number on Push events ?

I have found a workaround though by getting the pull request number using another query.

**Comment by Tomasz-Kluczkowski** [comment]
> > 
> 
> 
> 
> Hi @Tomasz-Kluczkowski 
> 
> 
> 
> Can you please let me know the query you used to get the pull request number on Push events ?
> 
> 
> 
> I have found a workaround though by getting the pull request number using another query.

Hi, 

I paste my workaround code below, hope it helps you or anyone else.

We use it in our pipeline and all is fine.

I am sending this from a mobile so formatting will probably be awkward ;).

Also I have this code in a  separate script to avoid polluting the main github workflow file with javascript code.


module.exports = async (github, context) => {
    // Get pull requests that are open for current ref.
    const pullRequests = await github.rest.pulls.list({
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: 'open',
        head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
    })

    // Set issue number for following calls from context (if on pull request event) or from above variable.
    const issueNumber = context.issue.number || pullRequests.data[0].number

    // Retrieve existing bot comments for the PR
    const {data: comments} = await github.rest.issues.listComments({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: issueNumber,
    })
    const botComment = comments.find(comment => {
        return comment.user.type === 'Bot' && comment.body.includes('Terraform Plan')
    })

    // Prepare format of the comment - it has to be de-indented to make markdown work properly.
    const output = `
#### Terraform Plan 📖 \`${process.env.TERRAFORM_PLAN_STEP_OUTCOME}\`

<hr>

*Pusher: @${context.actor}*
*Action: \`${context.eventName}\`*
*Workflow: \`${context.workflow}\`*
*Commit: \`${context.sha}\`*

<details><summary>Show Plan</summary>

\`\`\`\n
${process.env.TERRAFORM_PLAN}
\`\`\`

</details>`;

    // If we have a comment, update it, otherwise create a new one
    if (botComment) {
        github.rest.issues.updateComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: botComment.id,
            body: output
        })
    } else {
        github.rest.issues.createComment({
            issue_number: issueNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
        })
    }
}
