### ISSUE TITLE
GithubAction REPL

### ISSUE THREAD

**Issue by staabm** [actions/github-script#28]
Hey Guys.

thanks for this awesome Github Action. I have used Github Actions in a lot of projects and from time to time stumble over some very basic problems.

the actual deal breaker is the long feedback loop you get, when changing workflow files and waiting for the actual events which trigger them (most of the time we need to merge the workflows into the master branch, to trial and error with them).

thats a major pain.

after reading the README of this repo I thought about a REPL for Github Actions.

something like a website in which you can type your github workflow file, and let the REPL simulate a certain api event, so one can see the actual outcome (without the need to commit the workflow, merge it into master and wait for the actual events to happen).

not sure this is something which already exists (and I am not aware of).

also I am not sure this is something which should belong here... I will leave it here, maybe you guys know the right place to discuss this further.

**Comment by jclem** [comment]
Hey @staabm! This is a great idea, and it's something we've thought about some, too, although I can't give you a definite timeline or anything like that.

For the early beta of GitHub Actions, a lot of people used https://github.com/nektos/act to simulate their workflows in their local environment. It looks like it's been updated to work with the current version of Actions, which is great! I can't make any guarantees about whether it really works, and I don't think it totally reproduces the Actions runtime environment, but it may work for you, in the meantime!

For future reference, the [GitHub Actions Community Forum](https://github.community/t5/GitHub-Actions/bd-p/actions) is a great place for suggestions like this.
