### ISSUE TITLE
Update `octokit/rest.js` to include `actions`

### ISSUE THREAD

**Issue by simonjjones** [actions/github-script#29]
## Summary

Bump `octokit/rest.js` dependency to >= [16.40](https://github.com/octokit/rest.js/releases/tag/v16.40.0) to include `actions` endpoint methods.

### Notes

The [oktokit docs for v16](https://octokit.github.io/rest.js/v16#actions) already include the actions related methods, which led me to assume these would be available to the action.

**Comment by jclem** [comment]
This is fixed in 0.7.0
