### ISSUE TITLE
Retries not valid/ "Unexpected" input option 

### ISSUE THREAD

**Issue by sf-erush** [actions/github-script#290]
**Describe the bug**
Warning: Unexpected input(s) 'retries', valid inputs are ['script', 'github-token', 'debug', 'user-agent', 'previews', 'result-encoding']

**To Reproduce**
 uses: actions/github-script@v6
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          retries: 3
          script: |
               const { data: topics } =  await github.rest.repos.getAllTopics({
                        owner: 'SFMaps',
                        repo: repo
                    });

**Expected behavior**
Retry input option to be available as the per the documentation - https://github.com/actions/github-script#retries

**Desktop (please complete the following information):**

**Comment by joshmgross** [comment]
Sorry about that @sf-erush, the `v6` tag was still pointing to `v6.2.0` instead of `v6.3.0` which added support for retries.

I've updated `v6` https://github.com/actions/github-script/tags

Could you validate if it's working now?

**Comment by sf-erush** [comment]
@joshmgross Yes it looks to be working now! Thanks!
