### ISSUE TITLE
Current version (6.3.0) is overriding proxy configuration

### ISSUE THREAD

**Issue by r-antonio** [actions/github-script#291]
**Describe the bug**
With the update to 6.3.0 the requests are no longer going through the default proxy. Depending on the firewall and proxy configuration this would cause a connection timeout or other error.

**To Reproduce**
The steps may vary depending on the proxy and firewall.
1 - Configure a selfhosted runner with a default proxy
2 - Execute a workflow with this step:
```
steps:
    - uses: actions/github-script@v6.2.0
      with:
        script: |
          const {repo,owner} = context.repo;
          const response = await github.rest.pulls.list({owner,repo});
          console.log(response);
```

**Expected behavior**
The expected behaviour is that the action uses the default proxy. 

**Additional context**
The self-hosted runner's version is 2.297.0. Checking the code it seems that in [this](https://github.com/actions/github-script/blob/d4560e157075e2d93aa3022b5b51a42a880f1f93/src/main.ts#L43) line, `opts.request` is set as `{}` by default or `{ retries: <some-number> }` if retries are configured. This is just overriding the default values of `request` in [@actions/github](https://github.com/actions/toolkit/blob/192c26f865db0bb700aa0a40d193d08b57123949/packages/github/src/utils.ts#L15).

**Comment by joshmgross** [comment]
Released https://github.com/actions/github-script/releases/tag/v6.3.1 with this fixed.
