### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by drey0143143** [actions/github-script#304]
I'm getting this message when i use this action "actions/github-script@v6.0.0"

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout

**Comment by Malquias01** [comment]
> I'm getting this message when i use this action "actions/github-script@v6.0.0"
> 
> ```
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout
> ```

**Comment by joshmgross** [comment]
>Please update the following actions to use Node.js 16: actions/checkout

@drey0143143 it looks like `actions/checkout` is the reason for that deprecation, not `actions/github-script`. Could you update to a newer version of https://github.com/actions/checkout?

**Comment by drey0143143** [comment]
@joshmgross thanks for your answer.. your suggestion fixed the issue

**Comment by drey0143143** [comment]
I'm trying to send this message "Please make sure you review the changes in detail before approving this pull request" to reviewers in my repo before approving pull request. Can i use this action before or how do i tell github action to automatically find the reviewers that are already configured?
```
- uses: actions/github-script@v6
  id: my-script
  with:
    result-encoding: string
    retries: 3
    script: |
      github.rest.issues.get({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
      })

**Comment by joshmgross** [comment]
@drey0143143 you should be able to use this action to do that, but you'll likely need to make some API calls to fetch the configured reviewers.

https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request might be a good place to start.

I'd recommend reaching out to https://github.com/orgs/community/discussions/ or https://support.github.com/ if you need more assistance.
