### ISSUE TITLE
Add `fetch` parameter

### ISSUE THREAD

**Issue by mmkal** [actions/github-script#305]
**Is your feature request related to a problem? Please describe.**

It's often useful to mix-and-match github requests with requests to other services, e.g. the Vercel API, various internal APIs, etc. etc.

**Describe the solution you'd like**

Provide a `fetch` argument, just like `github`, `context`, `core`, `glob`, `io`, `exec` etc.

**Describe alternatives you've considered**

This issue seems to be trying to achieve a similar thing: https://github.com/actions/github-script/issues/272

I also tried using `github.request(...)` at first, but while you can hit non-GitHub APIs, it's impossible to override the `authorization` header, for example. If that's an issue, it's one for the octokit repo, though.

**Additional context**

`@octokit/request` [already depends on `node-fetch`](https://github.com/octokit/request.js/blob/2172a29e4f07a5c25534760c78c662c924b546af/package.json) so by using the same version, it wouldn't even add to the bundled size of this action, I don't think.

I'd be happy to open a PR for this if it would be accepted.

**Comment by danmichaelo** [comment]
Another alternative would be to upgrade to Node 18, which comes with global `fetch`.

**Comment by joshmgross** [comment]
> Another alternative would be to upgrade the action to Node 18, which comes with global `fetch`.

Only Node 12 (deprecated) and Node 16 are supported right now for actions - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing
