### ISSUE TITLE
Please fix set-output warning.

### ISSUE THREAD

**Issue by naruse666** [actions/github-script#315]
**I got warning like this.**
if my misunderstood, please let me know .
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/62323683/207537641-955f7ca5-c693-42a7-af34-8189b353c4af.png">

source:
[GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by joshmgross** [comment]
@naruse666 can you try using a newer version of `actions/github-script`?

**Comment by naruse666** [comment]
@joshmgross 
It's already fix it?
I'll try new version!
