### ISSUE TITLE
Question: Please clarify how is this action different than the preinstalled GitHub CLI on all GitHub-hosted runners

### ISSUE THREAD

**Issue by exalted** [actions/github-script#316]
GitHub CLI is [preinstalled](https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows) on all GitHub-hosted runners, so I'd appreciate knowing (and perhaps even put that info in the README) how is this action different that the preinstalled CLI's capabilities.

Thanks!

**Comment by joshmgross** [comment]
Both the GitHub CLI and this action serve similar purposes.

When using the gh CLI, you'd likely be using Bash or another shell scripting language to call the `gh` executable.
With this action, you're writing JavaScript.

As far as capabilities, this action includes some [Actions toolkit](https://www.github.com/actions/toolkit) modules that you wouldn't directly have access to in the `gh` cli.

**Comment by exalted** [comment]
Thank you for the clarification, @joshmgross !
