### ISSUE TITLE
Details/documentation on setting environment variables

### ISSUE THREAD

**Issue by MichaelJJ** [actions/github-script#327]
With the depreciation of setting output/environment variables via stdout, I was not able to find any details on how to set environment variables via a script. It's now required to append these variables to a file.

Could details be provided on how to properly set environment variables from a script that can be used in following steps?

Thank you.

**Comment by MichaelJJ** [comment]
Just stumbled across this: https://github.com/actions/toolkit/tree/main/packages/core#exporting-variables

**Comment by vincerubinetti** [comment]
It'd be great to add this to the readme here. But I guess judging by the number of 👍 s not many people are using to scripts to set environment variables...

**Comment by joshmgross** [comment]
@vincerubinetti feel free to submit a PR with the docs you'd like to see!
