### ISSUE TITLE
Update from v3 to v6

### ISSUE THREAD

**Issue by UVLabs** [actions/github-script#328]
The last time i used this library it was a v3 and I could have used it to create a tag. Here is an example of the job to do this:

 ```
- name: Create Tag
       uses: actions/github-script@v3
       env:
          TAG: ${{ steps.set-tag.outputs.tag_name }}
       with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.set-tag.outputs.tag_name }}",
              sha: context.sha
            })
```

I tried using v6 but when I do I get an error:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/10324144/213840151-eb942e3f-a462-4833-ab76-898cd7d3370c.png">

When i change back to v3 everything works fine. How can I migrate the code above to work with v6?

**Comment by joshmgross** [comment]
I suspect this is from the breaking changes in Octokit introduced in v5 of this action - https://github.com/actions/github-script#breaking-changes-in-v5

Could you try `github.rest.git.createRef`?

**Comment by UVLabs** [comment]
That worked thank you
