### ISSUE TITLE
V6 can only count till 100 files and not beyond that

### ISSUE THREAD

**Issue by irfanlai** [actions/github-script#330]
**Describe the bug**
I have a logic in my Actions YAML where when a PR is created. It goes and counts the file. If it finds files under 'force-app/' then it updates a value and if it finds files under 'vlocity/' the updates another value, also a combination of both.
It works fine until the files change are less than 100 under 'force-app/'
If my PR has 100 file changes under 'force-app/' and 20 files change under 'vlocity/' then it only updates the value for force-app. Logic is not able to count beyond 100 files.
Depending on the value my deployment job kicks off.
Code is below which I am using.

**To Reproduce**
Create a PR with 100 file changes under 'force-app/' and 20 files change under 'vlocity/' . Check the value which it shows 

**Expected behavior**
It should show value for both changes 

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu
  22.04.1

**Additional context**
```

- uses: actions/github-script@v6
        id: set-result
        with:
          script: |
              const result = await github.rest.pulls.listFiles({
                pull_number: context.payload.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: "100",
                });
            
                        
              var containsVlocity = "";            
              for(let file of result.data) {
                if(file.filename.includes("vlocity/") && !containsVlocity.includes("vlocity")){
                  containsVlocity = containsVlocity+"vlocity";
                }
                if(file.filename.includes("force-app/") && !containsVlocity.includes("sf")){
                  containsVlocity = containsVlocity+"sf";
                }
              }
              return containsVlocity
          result-encoding: string
          
      - name: Get result to debug
        run: echo "${{steps.set-result.outputs.result}}"

```

**Comment by joshmgross** [comment]
The API has a limit of 100 items per page, so you'll need to paginate the response. 

You can use https://github.com/octokit/plugin-paginate-rest.js/ for that

**Comment by irfanlai** [comment]
> The API has a limit of 100 items per page, so you'll need to paginate the response.
> 
> You can use https://github.com/octokit/plugin-paginate-rest.js/ for that

Thank you for the response. We did a workaround with logic.
