### ISSUE TITLE
Tag v6 is not pointing to latest (v6.4.0) release

### ISSUE THREAD

**Issue by lopes-gustavo** [actions/github-script#342]
**Describe the bug**
The tag `v6` is not currently pointing to the latest tag `v6.4.0`. 
This leads to `- uses: actions/github-script@v6` not having `fetch` and we need to fallback to `- uses: actions/github-script@v6.4.0`, locking the version.

**To Reproduce**
1. Create a workflow and add a step using `- uses: actions/github-script@v6`
2. Try to use `fetch`
3. See the error `ReferenceError: fetch is not defined`

**Expected behavior**
We should be able to use `fetch` as it's available on latest `v6`.

**Solution**
Update the tag `v6` to point to the same commit as `v6.4.0`

**Comment by joshmgross** [comment]
`v6` is now pointing to `v6.4.0`
