### ISSUE TITLE
Call workflows on the other repository with GITHUB_TOKEN

### ISSUE THREAD

**Issue by shmpwk** [actions/github-script#351]
**Is your feature request related to a problem? Please describe.**

As I understand, workflow_dispatch and repository_dispatch with GITHUB_TOKEN can call the other workflow.
However it seems we cannot call the workflow on **an other repository**.

The example is introduced at [GitHub Actions: Use the GITHUB_TOKEN with workflow_dispatch and repository_dispatch](https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch/)

```
name: Create Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml',
              ref: 'main',
            })
```

**Describe the solution you'd like**
call the workflow on an other repository.

**Describe alternatives you've considered**
Currently I end up using personal access token or Github Apps instead of GITHUB_TOKEN

**Additional context**

**Comment by mjpieters** [comment]
Your example workflow is not triggering a workflow on another repository, it uses `context.repo.repo`. The automatic GITHUB_TOKEN permissions never extend to other repositories, so I wouldn't expect you to be able to trigger a workflow in another repo with one, no.

This is the unfortunately not the right place to report issues with API permissions, unless you can show that you are able to trigger the workflow using the same token and octokit but not using this action. This action just bundles pcakages from `@action/toolkit` and lets you write javascript code inline in your workflow.

**Comment by shmpwk** [comment]
Got it, thank you!
