### ISSUE TITLE
author_association for issue_comment events doesn't return true association

### ISSUE THREAD

**Issue by emawby** [actions/github-script#365]
Context.payload.comment.author_association returns "contributor" even if the author is a "member" in the org. In my testing using Octokit this happens if you don't have an authenticated connection. Is there a way to setup the workflow so that it gets the correct association for a comment?

**To Reproduce**
1. Create a workflow that uses an "on issue comment" trigger in a public repo under an Org. 
2. Comment on that repo as a member account.
3. In the Context.payload.comment.author_association field the association will be "Contributor".
Pulling the issue comment via an authenticated session of Octokit you can see the association is now "Member".

**Comment by joshmgross** [comment]
👋 This is likely an issue with how GitHub Actions is scoped to a single repository, so it doesn't have privileges to know organization membership.

Changing that would be outside the scope of this action, so I'd recommend fetching the issue comment if that's a valid workaround.

If you'd like to provide feedback on this issue, I'd recommend going through https://github.com/orgs/community/discussions/categories/actions or https://support.github.com/
