### ISSUE TITLE
How to comment a markdown file on PR

### ISSUE THREAD

**Issue by Desiki-high** [actions/github-script#370]
## Why pull_request_traget?

It seems like only when we used the pull_request_target as the event, the action can comment on the PR.But I see some repo ci/cr could allow the github action bot comment on pull request , they don't need use the pull_request_target. You can see [this yml](https://github.com/dragonflyoss/Dragonfly2/tree/main/.github/workflows/cr.yml). 

So in the actions/github-script, can we used the pull_request event when we need to comment on PR? How to do that?

**Comment by Desiki-high** [comment]
my comment action error: Resource not accessible by integration, you can see [here](https://github.com/dragonflyoss/image-service/actions/runs/4739197938/jobs/8413885944). I just don't want to change the event to pull_request_target, maybe that is unsafe?

**Comment by joshmgross** [comment]
A workflow triggering on `pull_request` events from works can't have write permissions, unless it's a private repository and you've enabled that in settings. 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories

For your use case, you likely should use `pull_request_target`. It would be unsafe though if you're checking out code from the fork, so watch out for that.

**Comment by Desiki-high** [comment]
> A workflow triggering on `pull_request` events from works can't have write permissions, unless it's a private repository and you've enabled that in settings.
> 
> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories
> 
> For your use case, you likely should use `pull_request_target`. It would be unsafe though if you're checking out code from the fork, so watch out for that.

Thank you.

**Comment by Desiki-high** [comment]
When I use pull_request_target，the checkout action can only checkout from the master ？ I want to checkout from the pr commit, is any solutions?
