### ISSUE TITLE
Github Actions Check is attached to wrong job when job is triggered by workflow_dispatch event

### ISSUE THREAD

**Issue by froehr** [actions/github-script#379]
**Describe the bug**
When I create a check using the `github.rest.checks.create` function during a job run it is attached to the correct run if the job was triggered via a push but to the wrong job when the job was triggered via a workflow_dispatch event. In this case the "wrong job" means the last job that was triggered by a push instead the current run.

**To Reproduce**
I am creating a check using the actions/github-script@v6 action like so:

```
const response = await github.rest.checks.create({
  owner: context.repo.owner,
  repo: context.repo.repo,
  head_sha: context.sha,
  name: "${{inputs.name}}",
  status: "in_progress"
});
```

Afterwards I'm picking the check id from the response and update the check according to my run result like so:

```
await github.rest.checks.update({
  check_run_id: ${{inputs.id}},
  owner: context.repo.owner,
  repo: context.repo.repo,
  head_sha: context.sha,
  conclusion: "${{inputs.conclusion}}",
  output: {
    title: "${{inputs.output-title}}",
    summary: "summary",
  }
});
```

This is part of a composite action that can be reused. If I now use the composite action to create and update a check in a job that was triggered by a push everything works as expected. But if I trigger a manual run by a workflow_dispatch event the checks that are created during that run are attached to the last run that was started by a push event.

**Expected behavior**
Checks should always be connected to the runs they were created by independently if they were triggered my a PR, push or workflow_dispatch.

**Screenshots**

![example](https://user-images.githubusercontent.com/2845162/235871485-b0c031f3-181e-46f2-a1d3-49c63a482f88.png)
The image shows how all checks are attached to the last job that as triggered by a push.

**Additional info**
I have create to separate composite actions to reuse the check creation like so:

Create a check action:
```
name: Create new Status Check
description: Create a new Github Actions Status Check

inputs:
  name:
    required: true
    description: Set the name that the status check will have

outputs:
  status-id:
    description: The unique id of the status check. Can be used to update this check later
    value: ${{steps.create-status-check.outputs.result}}

runs:
  using: composite
  steps:
    - name: Create check based on image size
      id: create-status-check
      uses: actions/github-script@v6
      with:
        debug: true
        script: |
          console.log(context.repo.owner);
          console.log(context.repo.repo);
          console.log(context.sha);
          
          const response = await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head_sha: context.sha,
            name: "${{inputs.name}}",
            status: "in_progress"
          });
          
          return response.data.id;

```

Update a check action:
```
name: Update Status Check
description: Update a Github Actions Status check that was created previously

inputs:
  id:
    required: true
    description: The ID of the status check that needs to be updated
  conclusion:
    required: true
    description: The status that the check is set to. Possible values are action_required, cancelled, failure, neutral, success, skipped, stale, timed_out
  output-title:
    required: true
    description: The title of the status check that is shown in the check overview

runs:
  using: composite
  steps:
    - name: Create check based on image size
      uses: actions/github-script@v6
      with:
        script: |          
          await github.rest.checks.update({
            check_run_id: ${{inputs.id}},
            owner: context.repo.owner,
            repo: context.repo.repo,
            head_sha: context.sha,
            conclusion: "${{inputs.conclusion}}",
            output: {
              title: "${{inputs.output-title}}",
              summary: "summary",
            }
          });
```

**Comment by joshmgross** [comment]
Hey @froehr, I believe this is a known limitation with using the checks API on Actions runs. As far as I know, that's not something we officially support.

Since this isn't an issue with `actions/github-script`, I'd recommend going through https://support.github.com/ or the GitHub Community - https://github.com/orgs/community/discussions/categories/actions

**Comment by froehr** [comment]
I will open a ticket, thank you.
But saying that this kind of API behavior is a "known limitation" feels a bit awkward in all honesty. Feels very much like a bug.
