### ISSUE TITLE
@actions/artifact as part of the github-script

### ISSUE THREAD

**Issue by y-nk** [actions/github-script#395]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated by the arbitrary choice of libraries included/not-included in the github-script action.

**Describe the solution you'd like**
add all the @actions/* npm packages, or make it configurable which are preinstalled and linked with a `with` option (default as now, so no breaking change)

**Describe alternatives you've considered**
using `npm install` but this really kills the conveniency of this action. at this point i can just `npm install @actions/core @actions/github` etc etc..., so it's better not to do it.

**Comment by joshmgross** [comment]
This was previously discussed in #120

> For packages like `@actions/cache` and `@actions/artifact`, I would expect a fair bit of code to use those fully and would be better off used in their own action.


There's also the concern about drastically increasing the size of this action, which slows down every run using `actions/github-script` even if the additional libraries aren't used.

**Comment by y-nk** [comment]
fair point. thanks for your feedback and linking with #120 🙏

**Comment by iTrooz** [comment]
This could be solved by adding a `additionalDependencies` parameter to the action, which would be a helper to make a cached `npm install` call at runtime. It would be longer, but I think the tradeoff is worth it

If this repository starts accepting contributions again, I could submit a PR for that
