### ISSUE TITLE
github.repos.deleteDeployment is not a function

### ISSUE THREAD

**Issue by koistya** [actions/github-script#40]

**Comment by jclem** [comment]
This likely just means we need to update dependencies in `@actions/core` or we need to update `@actions/core` in this repo. I'm temporarily on another project but will come back to this ASAP.

**Comment by jclem** [comment]
Confirmed that @actions/github's version of @octokit/rest is a little behind https://github.com/actions/toolkit/blob/a67b91ea15598bea0bbf639ef4e91916feab0c69/packages/github/package.json#L42

**Comment by jclem** [comment]
This will be fixed once this draft PR lands https://github.com/actions/toolkit/pull/453. At that point, I'll release a new version of github-script. Leaving this open until then.

**Comment by localheinz** [comment]
@jclem 

Looking forward to it!

🤓

**Comment by jclem** [comment]
This should now be available in v2:

```yaml
- uses: actions/github-script@v2
```
