### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' (at main.c14547ae.js:1:1)

### ISSUE THREAD

**Issue by Nimmi-wal** [actions/github-script#405]
**Describe the bug**
Uncaught SyntaxError: Unexpected token '<' (at main.c14547ae.js:1:1)

**To Reproduce**
Deployed application using github actions
<img width="644" alt="image" src="https://github.com/actions/github-script/assets/117816375/00271bc3-9a5b-47c8-b7c2-c2cfe75e865f">

**Comment by joshmgross** [comment]
This doesn't appear to be an issue with this action - feel free to reopen with some more details and an example of your workflow.
