### ISSUE TITLE
`Resource not accessible by integration` when calling `github.rest.repos.updateBranchProtection` using GitHub App

### ISSUE THREAD

**Issue by Flasheh** [actions/github-script#410]
**Describe the bug**
Hello, I am trying to update the branch protection settings on a repository from within a github actions workflow. However I seem to have permission issues when trying to authenticate with a GitHub App.

My github app has Administration "write" permissions so that should be ok.

**To Reproduce**

Github workflow steps, these steps are called from a composite action.
```
    - name: Get App token
      id: app-token
      uses: getsentry/action-github-app-token@v2.0.0
      with:
        app_id: ${{ inputs.gitAppId }}
        private_key: ${{ inputs.gitAppKey }}

    - name: Update branch protection
      uses: actions/github-script@v6
      with:
        github-token: ${{ steps.app-token.outputs.token }}
        script: |
          const version = 'testbranch'

          github.rest.repos.updateBranchProtection({
            owner: context.repo.owner,
            repo: context.repo.repo,
            branch: version,
            required_status_checks: {
              strict: false,
              contexts: []
            },
            enforce_admins: false,
            required_pull_request_reviews: null,
            restrictions: {
              users: [],
              teams: [
                'team1',
                'team2'
              ],
              apps: []
            }
          })
```

Workflow logs:
```
RequestError [HttpError]: Resource not accessible by integration
    at /runner/_work/_actions/actions/github-script/v6/dist/index.js:6842:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/<snip>/<snip>/branches/testbranch/protection',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Wed, 09 Aug 2023 15:03:45 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '<snip>,
      'x-ratelimit-limit': '15000',
      'x-ratelimit-remaining': '14997',
      'x-ratelimit-reset': '1691595321',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '3',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/branches/branch-protection#update-branch-protection'
    }
  },
  request: {
    method: 'PUT',
    url: 'https://api.github.com/repos/<snip>/<snip>/branches/testbranch/protection',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/github-script octokit-core.js/3.6.0 Node.js/16.16.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"required_status_checks":{"strict":false,"contexts":[]},"enforce_admins":false,"required_pull_request_reviews":null,"restrictions":{"users":[],"teams":["team1","team2"],"apps":[]}}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}
```

**Expected behavior**
I would like to change my branch protection settings while authenticating with a github app.

**Comment by Flasheh** [comment]
Found permissions issue

**Comment by cjk7989** [comment]
Hi @Flasheh, I will be very appreciate if you could share which permission issue you got, since I meet a similar issue which may related to github-token

Here is my workflow:

- name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ env.NPM_PACKAGE_VERSION }}",
              sha: "${{ env.GIT_COMMIT_SHA }}"
            })

**Comment by Flasheh** [comment]
Hey @cjk7989 

The GitHub App I used there was missing some permission but I don't remember exactly what.
Although I see that you're just using your workflow's GITHUB_TOKEN not a seperate app, and you're only creating a git tag. So the permissions are different anyways. I was editing branch protections which require some admin-level permissions on the repo.

**Comment by cjk7989** [comment]
> Hey @cjk7989
> 
> The GitHub App I used there was missing some permission but I don't remember exactly what. Although I see that you're just using your workflow's GITHUB_TOKEN not a seperate app, and you're only creating a git tag. So the permissions are different anyways. I was editing branch protections which require some admin-level permissions on the repo.

Thanks very much for your reply! The issue is actually due to the lack of permissions. I can't point out which permissions I need to set to "write", but I just resolved it by adding:
```
permissions: write-all
```
to my workflow file.

**Comment by Flasheh** [comment]
If all you're doing is creating a git ref I think you just need write for 'contents'
```yaml
permissions:
   contents: write
```

**Comment by rpioger** [comment]
I've been using this action and figured that my case required to use my own PAT. I'm not sure how GITHUB_TOKEN is configured, but it seemed to not be enough to read variables (even with the right read-write permissions setup in the settings). Instead I had to set up a specific PAT to use successfully the following action
`
- name: Fetch repository secrets and variables
      id: secrets_variables
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.MY_PAT_READ_ONLY }}
        script: |
          const response = await github.request('GET /repos/${{ github.repository }}/actions/variables');
          return response.data.variables.map(variable => variable.name);
`
