### ISSUE TITLE
`Resource not accessible by integration` when trying examples

### ISSUE THREAD

**Issue by tiziano88** [actions/github-script#42]
Namely, I am trying the [Welcome a first-time contributor](https://github.com/actions/github-script#welcome-a-first-time-contributor) example, but I suspect because it operates on a PR, it gets a read-only token, and therefore it fails. Or am I missing something else?

**Comment by jclem** [comment]
For the time being, this is the case if the PR is from a fork of the repository. It's on the roadmap to change how that works, but currently that example will not function unless the PR is from a collaborator.

I'm going to consider removing the example until that's fixed.

**Comment by BastianZim** [comment]
@jclem Would it be possible to keep this issue open until that's possible? Just to have a place to follow along.

**Comment by dgurns** [comment]
I solved this by going to Settings > Actions and giving read + write permissions to workflows.

**Comment by dineshba** [comment]
I solved it by adding below lines in the workflow
```yaml
permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'
  ```

**Comment by paulodiovani** [comment]
> I solved it by adding below lines in the workflow
> 
> permissions:
>   pull-requests: 'write'

This could be included in the examples.
