### ISSUE TITLE
Unable to resolve action `actions/github-script@v7`, unable to find version `v7`

### ISSUE THREAD

**Issue by im-sampm** [actions/github-script#442]
**Describe the bug**
I am attempting to use v7 but I get the following error:

![image](https://github.com/actions/github-script/assets/140651156/5fcb5a38-873b-4142-9b00-8e1d2508d523)

**To Reproduce**

Create an Action step as follows:
```
    - id: main
      uses: actions/github-script@v7
      continue-on-error: true
      with:
        github-token: ${{ inputs.SECURITY_TOKEN }}
        retries: 3
        base-url: https://api.${{ inputs.HOSTNAME }}
        script: |
          return github.rest.repos.update( ${{ inputs.PAYLOAD }} );
```

**Expected behavior**
I expect this to work.

**Screenshots**

**Additional context**
This issue only happens when using @v7 on our GHES instance.  Testing against GHEC does not results in this error (strangely).

**Comment by v7** [comment]
Sorry bro my bad

**Comment by SciC0Mantis** [comment]
My bad
As well

**Comment by im-sampm** [comment]
@joshmgross Thanks Josh, this was indeed the issue and the link you provided helped us resolve the problem.

Thanks again!

**Comment by thoshna** [comment]
Unable to resolve action `thoshna/ci-cd-pipeline@v3`, unable to find version `v3`
