### ISSUE TITLE
Can't seem to trigger a job based on text in the opening comment

### ISSUE THREAD

**Issue by guardrex** [actions/github-script#496]
@joshmgross ... Hello! Could you help me again with a thorny conditional check for running a job? Earlier, we were working with [conditionals for issue labels](https://github.com/actions/github-script/issues/441). Now, I need to run a job based on opening issue body content.

Our situation for Microsoft ASP.NET Core docs (the official doc set) is that we're having some instability on getting a tool called "Repoman" to run and apply labels correctly to newly opened issues. The maintainer of Repoman thinks that there has been some changes in hosting that are interfering with that tool running. When Repoman works, it applies some opening labels, and then my GH workflow sees one of the labels (`blazor/subsvc`) and runs a job. Since Repoman is having trouble getting labels affixed to issues when they're opened, I'm looking for a way for my workflow to run directly and not use Repoman's applied labels.

We have some stable body content (a URL in the opening issue comment) that I can search for.

Here's an example issue: https://github.com/dotnet/AspNetCore.Docs/issues/33931

You see there that we have the article link in the body of the opening comment. For example, any Blazor issue that's opened will have a link like this ...

> https://learn.microsoft.com/en-us/aspnet/core/blazor/...?view=aspnetcore-8.0

... in the body of the opening comment, so I think if I can just compose an `if:` to find the text "`aspnet/core/blazor`" that I would be able to get my jobs to run.

Therefore, I'm trying `if: contains(github.event.comment.body, 'aspnet/core/blazor')`. Below, I'm showing the line change from looking at a label to a line that checks the body content. However, that change didn't work in testing. It doesn't throw an error, but the conditional fails and the job doesn't run.

Can you see where I'm going wrong with that `if:` statement? I suspect the check on `github.event.comment.body` is incorrect. I've checked the API docs, but I find it difficult to understand the chaining of properties on the context (`github.event`) for simple use case scenarios like this. I still wish there were many more `if:` examples for common use cases in the docs. Anyway, can you give me a tip on getting this approach to work?

```diff
name: Issue processing
on:
  issues:
    types:
      - opened
jobs:
  process-blazor-issue:
-   if: github.event.label.name == 'blazor/subsvc'
+   if: contains(github.event.comment.body, 'aspnet/core/blazor')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await ...
            await ...
            await ...
            await ...
            await ...
            await ...
```

**Comment by joshmgross** [comment]
👋 Hey @guardrex,

Does it work if you use `github.event.issue.body`?


https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=opened#issues is a good reference for what we have in these event payloads, and you can also log out the whole event in a separate job to debug these sort of things:

```yaml
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#example-printing-context-information-to-the-log

**Comment by guardrex** [comment]
Thanks @joshmgross ... I'll try that now and report back.

**Comment by guardrex** [comment]
BTW while I'm waiting for that change to go in ...

That section of the API docs is ***very cryptic*** ... there is no `body` listed there, so `github.event.issue.body` doesn't seem like a thing. One would think perhaps that `github.event.issues.issue.body` might work ... but I think I tried that and it didn't work.

Generally speaking, I've had trouble getting my `if` statements right based on the current docs. I wish for more recipe-type/how-to types of examples that would show how to make simple checks on issues/PRs like this.

**Comment by guardrex** [comment]
# 🎉 ***Yes!*** 🍻 

That lick'd IT! ...

https://github.com/dotnet/AspNetCore.Docs/issues/33953

Thanks again for your help @joshmgross! May the server gods 🙏 bless you!

Closing now as resolved, but I hope the powers that be around here realize that the docs aren't good enough for cases like this. More how-to basic examples would be very helpful on getting these `if:` conditionals correct.

**Comment by joshmgross** [comment]
> That section of the API docs is _**very cryptic**_ ... there is no `body` listed there, so `github.event.issue.body` doesn't seem like a thing. One would think perhaps that `github.event.issues.issue.body` might work ... but I think I tried that and it didn't work.

Yep, I can see how that could be confusing.

For context, everything after `github.event` will match the full event payload. `issues` is the name of the event, but Actions will not include that in the context name.

If it helps, the Actions VS Code extension will do some validation on the expression context for you along with auto-complete

https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions

![VS Code extension expression validation](https://github.com/user-attachments/assets/1ccead72-b637-4755-9d62-c30d67644693)

![VS Code extension expression auto-complete](https://github.com/user-attachments/assets/c7a9716a-851d-4e12-92dd-d172cb229f1d)

Feel free to file an issue in https://github.com/github/docs/issues for that feedback though.
