### ISSUE TITLE
github.repos.deleteDeployKey is not a function

### ISSUE THREAD

**Issue by max4t** [actions/github-script#58]
Everything is in the title :)
[Octokit doc](https://octokit.github.io/rest.js/v17#repos-delete-deploy-key)

**Comment by jclem** [comment]
This isn't updated in lockstep with new releases of http://npm.im/@octokit/plugin-rest-endpoint-methods (in fact `deleteDeployKey` was added over the weekend less than 24 hours ago), as we rely on releases of https://npm.im/@actions/github for those dependencies.

When @actions/github is updated to use [@octokit/plugin-rest-endpoint-methods v3.17.0](https://github.com/actions/toolkit/issues/496), I'll update this action, as well.

**Comment by max4t** [comment]
Oh! My bad, I didn't see it has been just released.
I'll use `removeDeployKey` then.
Thanks!

**Comment by jclem** [comment]
@max4t I realized I can solve this sooner by making @octokit/* dependencies direct dependencies here instead of transitive. I should be able to land https://github.com/actions/github-script/pull/59 tomorrow and resolve this.

**Comment by jclem** [comment]
(Reopened since I haven't done a release, yet). Just to confirm @max4t can you test your workflow with `uses: actions/github-script@82b33c8`? The `deleteDeployKey` method should be available there.

**Comment by moop-moop** [comment]
`uses: actions/github-script@82b33c8` fixed my issue with
 `createStatus` 
https://octokit.github.io/rest.js/v16#repos-create-status 
versus `createCommitStatus`
https://octokit.github.io/rest.js/v18#repos-create-commit-status
