### ISSUE TITLE
Comment api endpoint broken

### ISSUE THREAD

**Issue by aulneau** [actions/github-script#66]
Hi there! Great little action, I have used it in a few of our projects to automatically generate some comments on new PRs. It works great in one repo, but in another, the api request seems to fail with a duplicate `/` in the url:

```js
    method: 'GET',
    url: 'https://api.github.com/repos/***/docs.***/issues//comments',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit-core.js/2.5.3 Node.js/12.13.1 (Linux 5.3; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: [Agent], hook: [Function: bound bound register] }
```

Notice how it's `   url: 'https://api.github.com/repos/***/docs.***/issues//comments',` vs `.../issues/comments`. You can see the [broken code here](https://github.com/blockstack/docs.blockstack/blob/ca042d4ddf9fff2c73ee5b803a6953452f2ff4c1/.github/workflows/deploy.yml#L17 ) and the same, [working code (slightly different syntax) here](https://github.com/blockstack/ux/blob/master/.github/workflows/deploy-docs.yml#L39)

**Comment by jclem** [comment]
Hey @aulneau thank you for reporting this! This issue should be opened against the [octokit/rest.js](https://github.com/octokit/rest.js/) repository. I don't maintain that project, it's just a dependency of this action 😄

**Comment by aulneau** [comment]
Hi there @jclem, it seems as though this is not an issue in the octokit/rest repo, but an issue with the context object not containing the data it should. Do you know why it might not contain an issue number? you can see the log of `context` here https://github.com/blockstack/docs.blockstack/runs/878974240?check_suite_focus=true

**Comment by jclem** [comment]
@aulneau Ah, I see what's happening now! Sorry for the misdirection. This workflow is running on `push` as well as `pull_request`. The `push` event won't have information about any pull request in it, so the number isn't present. The `pull_request` workflow will run when the pull request branch is synced to, so there's no need for `push`, unless you have it there for some other reason. 

Let me know if that helps!

**Comment by aulneau** [comment]
hmm I see -- I added `push` because when I added anything to the pull request, the action would _not_ fire.

**Comment by jclem** [comment]
Hey @aulneau in this case, I believe that is due to the merge conflict on https://github.com/blockstack/docs.blockstack/pull/655. When there's a merge conflict on a PR, there's not merge commit, which is the SHA that Actions uses to run the workflow from. If we just ran on the head of the PR branch itself, for example, the workflow wouldn't represent the state of the PR if it were merged at that point.

**Comment by aulneau** [comment]
@jclem ah, perfect, that was the issue. Didn't realize that conflicts affected things in such a way, good to know! I appreciate your help!

**Comment by bernhardkaindl** [comment]
In my case, the URL was correct, but self-hosted github-runners need to get explicit permission in the `.github/workflows/yourfile.yaml`:
```yaml
permissions:
  pull-requests: write  # Needed for creating comments in pull-requests thru the API
  statuses: write  # Needed in case the github action wants to set the commit pending state
````
