### ISSUE TITLE
Dependencies are outdated

### ISSUE THREAD

**Issue by rossjrw** [actions/github-script#72]
github-script's dependencies for Octokit are outdated (#59). `@actions/github` is listed as version 3.0.0, which is a full version behind the latest. The latest version of Octokit removes deprecated methods which haven't even been deprecated yet. Although these methods [are still documented](https://octokit.github.io/rest.js/v16) as of writing, this caused a moment of confusion for me. Please consider updating!

**Comment by jclem** [comment]
Thanks for notifying me of this @rossjrw. I update them semi-regularly and am definitely due for another update. I happily accept PRs on changes like this, and will try to get to it myself this week.

**Comment by jclem** [comment]
These are in the v3 release.
