### ISSUE TITLE
createComment 404 Error

### ISSUE THREAD

**Issue by RoyalSix** [actions/github-script#77]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

This is my yml file and it is resulting in the following error
```
    steps:
      - name: "test comment"
        uses: actions/github-script@v2.0.0
        with:
          github-token: ${{secrets.ACTIONS_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'test'
            })

```
Error:
```
##[error]Unhandled error: HttpError: Not Found
...
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/xxxxx/xxxxxxx/issues//comments',
```

Seems like there is a url path issue. Note the double slash after issues.

**Comment by RoyalSix** [comment]
Looking at the source now I can see my issue_number field is returning blank

**Comment by Detective-Khalifah** [comment]
> Looking at the source now I can see my issue_number field is returning blank

What's the fix/workaround to get by this?

**Comment by MikeSoft** [comment]
i have the same error

**Comment by MikeSoft** [comment]
I found a solution for my error.

use:
`
on:
  pull_request:
    types: [ opened, reopened, edited ]
`

Instead of:
`
on:
  push:
`
