### ISSUE TITLE
eslint-plugin-actions: ESLint plugin to lint inline scripts in workflow

### ISSUE THREAD

**Issue by ylemkimon** [actions/github-script#82]
(Not really an issue)

First of all, thank you for the great action!

Inlining scripts in the workflow file has perks like not having to checkout the repo, but maintainability is an issue. (#38) So I've created [`eslint-plugin-actions`](https://github.com/ylemkimon/eslint-plugin-actions), an ESLint plugin to allow linting inline scripts in literal blocks (`|`) of workflow files.

![A JS script in a GitHub workflow editor has red squiggly underlines. A tooltip explains the problem.](https://github.com/ylemkimon/eslint-plugin-actions/raw/master/screenshot.png)

Please feel free to share your comments and feedback!

If appropriate, it'd be nice to add a link to the project in `README`.

**Comment by jclem** [comment]
Whoa! This is awesome @ylemkimon. I'm going to close the issue just for my own tracking purposes, but I will definitely give it a whirl and pass it along to others I think might be interested.
