### ISSUE TITLE
Add GraphQL client in the inputs too

### ISSUE THREAD

**Issue by quilicicf** [actions/github-script#90]
**Is your feature request related to a problem? Please describe.**

Hi, I'd like to use this GitHub Action to organize a GitHub project when issues are labeled/unlabeled/closed/created. 

My issue is that the workflow reacts on a trigger on the issue and I can't easily/efficiently make a link to the associated project cards with the REST API of GitHub.

**Describe the solution you'd like**

I think it would be much more powerful if we could use a mix of GraphQL and REST calls. 

To do so, I suggest to pass both clients as input to the script in the action. The parameter `github` could be deprecated and parameters `rest` and `graphql` added (minor update). 

When you release a breaking version later on, you could remove the parameter `github`.

**Describe alternatives you've considered**

The only other alternative I see would be to write my own action. I could but my use-case seems to fit into the mission of `github-script` so I think that the community would benefit from it being unlocked here.

**Additional context**

I'd be willing to submit a PR.

I have never worked on GitHub actions before, seems like a great opportunity to discover how it works (and I could add a non-spammy contribution to Hacktoberfest :laughing: ).

**Comment by jclem** [comment]
This action already provides a GraphQL client, please see [this section of the readme](https://github.com/actions/github-script#run-custom-graphql-queries). The `github` object is an instance of [octokit/core](https://www.npmjs.com/package/@octokit/core) with some additional plugins (the REST API methods, pagination).

**Comment by quilicicf** [comment]
Oops, sorry for that, skimmed the doc a bit too fast :facepalm:

**Comment by jclem** [comment]
No worries!
