### ISSUE TITLE
createRelease and GITHUB_REF

### ISSUE THREAD

**Issue by qbaj** [actions/github-script#93]
Hi, I'd like to create automatically pre-release from tag. I use YAML below to do it. 
My tag is `v_test` and it is on the release list like tag `releases/tag/v_test`, not release yet. 
After createRelease there is still only tag, but no release. Function createRelease returns code 201, so release was created, but it is not available on release list. On the release list, there is only tag.
Surprisingly, release is available with tag name `refs/tags/v_test` and it is on `/releases/tag/refs/tags/v_test`.
I think, problem is with `tag_name` or `createRelease`.

```
name: RELEASE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v2
      - name: PRERELEASE
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { repo: { owner, repo }, sha } = context;
            const release = await github.repos.createRelease({
                owner, repo,
                tag_name: process.env.GITHUB_REF,
                prerelease: true
            });
```

I solved it, by modification `tag_name` with YAML below to cut last part of tag name:
```
name: RELEASE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v2
      - name: PRERELEASE
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { repo: { owner, repo }, sha } = context;
            const tag = process.env.GITHUB_REF.split('/').slice(-1)[0];
            const release = await github.repos.createRelease({
                owner, repo,
                tag_name: tag ,
                prerelease: true
            });
```

**Comment by jclem** [comment]
Hi @qbaj this looks like an issue with Octokit or the API, but not github-script. The `createRelease` function you're calling is part of Octokit. The best place to ask a general question like this is probably in the [GitHub Actions support community](https://github.community/c/github-actions/41).
